# Setup
title:               Group Narratives
tagline:             'group dynamics in business'
description:         'Consulting in New Zealand and online in project management group dynamics and stakeholder management'
url:                 https://groupnarratives.co.nz
baseurl:             /
paginate:            5
permalink:           pretty

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:title/

# About/contact
author:
  name:              Gerald Lee Jordan
  url:               https://twitter.com/groupnarratives
  email:             geraldleejordan@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.0.0
google_analytics_id: #UA-XXXX-Y
timezone: Pacific/Auckland
future: false
